import type { Metadata } from "next";

import "./globals.css";
import { getLocale, getMessages } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import localFont from "next/font/local";
import ReduxProvider from "@/lib/store/ReduxProvider";

const madani = localFont({
  src: [
    { path: "../fonts/alfont_com_Madani-Arabic-Bold-2.ttf", weight: "700" },
    { path: "../fonts/alfont_com_Madani-Arabic-Semi-Bold-1.woff", weight: "600" },
    { path: "../fonts/alfont_com_Madani-Arabic-Medium-1.woff", weight: "500" },
    { path: "../fonts/alfont_com_Madani-Arabic-Regular.woff", weight: "400" },
    { path: "../fonts/alfont_com_Madani-Arabic-Light.woff", weight: "300" },
  ],
});


export const metadata: Metadata = {
  title: "Prolancer",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const locale = await getLocale();
  const messages = await getMessages();
  return (
    <html lang={locale} dir={locale === "ar" ? "rtl" : "ltr"}>
      <body className={`${madani.className} antialiased`}>
        <NextIntlClientProvider messages={messages}>
          <ReduxProvider>
            {children}
          </ReduxProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
